import sqlite3
import json
import os
from collections import defaultdict

def run_dashboard(db_file="logs/warehouse_sim.db"):
    if not os.path.exists(db_file):
        print(f"Database file {db_file} not found.")
        return

    print(f"Loading logs from {db_file}...")
    
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    # Schema: id, timestamp, agent_id, action, state, state_hash, reward, metadata
    cursor.execute("SELECT agent_id, reward, metadata FROM interactions")
    rows = cursor.fetchall()
    conn.close()
    
    # Metrics
    collisions = 0
    total_delivered = 0
    total_pickups = 0
    battery_depletions = 0
    agent_rewards = defaultdict(float)
    agent_steps = defaultdict(int)
    
    total_steps = len(rows)

    for r in rows:
        agent_id = r[0]
        reward = r[1]
        meta_json = r[2]
        
        try:
            meta = json.loads(meta_json)
        except:
            meta = {}
            
        agent_steps[agent_id] += 1
        agent_rewards[agent_id] += reward
        
        evt = meta.get("event")
        if evt == "delivered":
            total_delivered += 1
        elif evt == "picked_up":
            total_pickups += 1
        elif evt == "battery_depleted":
            battery_depletions += 1
        elif evt == "collision":
            collisions += 1
            
    # Display
    print("\n" + "="*40)
    print(" WAREHOUSE LOGISTICS DASHBOARD ")
    print("="*40)
    print(f"Total Steps:           {total_steps}")
    print("-" * 40)
    print(" SUCCESS METRICS")
    print(f"Items Delivered:       {total_delivered}")
    # Approximate TPM assuming 30s run for current logs, but ideally we get time delta
    print(f"Items Picked Up:       {total_pickups}")
    print("-" * 40)
    print(" FAILURE MODES")
    print(f"Collisions:            {collisions}")
    if total_steps > 0:
        print(f"Collision Rate:        {(collisions/total_steps)*100:.2f}%")
    print(f"Battery Depletions:    {battery_depletions}")
    print("-" * 40)
    print(" AGENT PERFORMANCE")
    print(f"{'Agent ID':<20} | {'Steps':<8} | {'Rwrd':<8} | {'Eff (Stp/Del)':<15}")
    print("-" * 40)
    
    # Calculate per-agent deliveries? We need to track it per agent if we want efficiency per agent
    # For MVP we just show global steps.
    for agent_id, steps in agent_steps.items():
        print(f"{agent_id:<20} | {steps:<8} | {agent_rewards[agent_id]:.1f}     | N/A")
    print("="*40 + "\n")
    
    # Generate Markdown Report for Stakeholders
    report_file = "warehouse_report.md"
    with open(report_file, "w") as f:
        f.write("# Warehouse Operations Report\n\n")
        f.write("**Status**: Generated Automatically\n")
        f.write(f"**Total Steps Analyzed**: {total_steps}\n\n")
        
        f.write("## Executive Summary\n")
        safety_score = max(0, 100 - (collisions * 10) - (battery_depletions * 50))
        f.write(f"- **Safety Score**: {safety_score}/100\n")
        f.write(f"- **Throughput**: {total_delivered} Packages Delivered\n")
        if total_steps > 0:
            eff = (total_delivered / total_steps) * 100
            f.write(f"- **Efficiency Index**: {eff:.2f} (Del/Step)\n")
        
        f.write("\n## Incident Log (Risk Analysis)\n")
        if collisions == 0 and battery_depletions == 0:
            f.write("> :white_check_mark: **No Critical Incidents Detected.** Operations are nominal.\n")
        else:
            if collisions > 0:
                f.write(f"> :warning: **Safety Violation**: {collisions} Collision Events detected. Review pathfinding logic.\n")
            if battery_depletions > 0:
                f.write(f"> :rotating_light: **Critical Failure**: {battery_depletions} Robots died due to starvation. Increase charger capacity immediately.\n")
        
        f.write("\n## Fleet Performance\n")
        f.write("| Agent ID | Steps Active | Contribution (Reward) | Status |\n")
        f.write("|----------|--------------|-----------------------|--------|\n")
        for agent_id, steps in agent_steps.items():
            r = agent_rewards[agent_id]
            status = "Online"
            f.write(f"| {agent_id} | {steps} | {r:.1f} | {status} |\n")
            
        f.write("\n---\n*Report generated by Logistics Dashboard v1.0*")
    
    print(f"Report generated: {os.path.abspath(report_file)}")

if __name__ == "__main__":
    run_dashboard()
